require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KeyMappingsController do

  # This should return the minimal set of attributes required to create a valid
  # KeyMapping. As you add validations to KeyMapping, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all key_mappings as @key_mappings" do
      key_mapping = KeyMapping.create! valid_attributes
      get :index
      assigns(:key_mappings).should eq([key_mapping])
    end
  end

  describe "GET show" do
    it "assigns the requested key_mapping as @key_mapping" do
      key_mapping = KeyMapping.create! valid_attributes
      get :show, :id => key_mapping.id.to_s
      assigns(:key_mapping).should eq(key_mapping)
    end
  end

  describe "GET new" do
    it "assigns a new key_mapping as @key_mapping" do
      get :new
      assigns(:key_mapping).should be_a_new(KeyMapping)
    end
  end

  describe "GET edit" do
    it "assigns the requested key_mapping as @key_mapping" do
      key_mapping = KeyMapping.create! valid_attributes
      get :edit, :id => key_mapping.id.to_s
      assigns(:key_mapping).should eq(key_mapping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KeyMapping" do
        expect {
          post :create, :key_mapping => valid_attributes
        }.to change(KeyMapping, :count).by(1)
      end

      it "assigns a newly created key_mapping as @key_mapping" do
        post :create, :key_mapping => valid_attributes
        assigns(:key_mapping).should be_a(KeyMapping)
        assigns(:key_mapping).should be_persisted
      end

      it "redirects to the created key_mapping" do
        post :create, :key_mapping => valid_attributes
        response.should redirect_to(KeyMapping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved key_mapping as @key_mapping" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeyMapping.any_instance.stub(:save).and_return(false)
        post :create, :key_mapping => {}
        assigns(:key_mapping).should be_a_new(KeyMapping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KeyMapping.any_instance.stub(:save).and_return(false)
        post :create, :key_mapping => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested key_mapping" do
        key_mapping = KeyMapping.create! valid_attributes
        # Assuming there are no other key_mappings in the database, this
        # specifies that the KeyMapping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KeyMapping.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => key_mapping.id, :key_mapping => {'these' => 'params'}
      end

      it "assigns the requested key_mapping as @key_mapping" do
        key_mapping = KeyMapping.create! valid_attributes
        put :update, :id => key_mapping.id, :key_mapping => valid_attributes
        assigns(:key_mapping).should eq(key_mapping)
      end

      it "redirects to the key_mapping" do
        key_mapping = KeyMapping.create! valid_attributes
        put :update, :id => key_mapping.id, :key_mapping => valid_attributes
        response.should redirect_to(key_mapping)
      end
    end

    describe "with invalid params" do
      it "assigns the key_mapping as @key_mapping" do
        key_mapping = KeyMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeyMapping.any_instance.stub(:save).and_return(false)
        put :update, :id => key_mapping.id.to_s, :key_mapping => {}
        assigns(:key_mapping).should eq(key_mapping)
      end

      it "re-renders the 'edit' template" do
        key_mapping = KeyMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KeyMapping.any_instance.stub(:save).and_return(false)
        put :update, :id => key_mapping.id.to_s, :key_mapping => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested key_mapping" do
      key_mapping = KeyMapping.create! valid_attributes
      expect {
        delete :destroy, :id => key_mapping.id.to_s
      }.to change(KeyMapping, :count).by(-1)
    end

    it "redirects to the key_mappings list" do
      key_mapping = KeyMapping.create! valid_attributes
      delete :destroy, :id => key_mapping.id.to_s
      response.should redirect_to(key_mappings_url)
    end
  end

end
